# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  websockify:
    image: kamehb/websockify
    restart: unless-stopped
    command: "0.0.0.0:6432 db:5432"
    ports:
      - "6432:6432"
    depends_on:
      - db
    volumes:
      - websockify-data:/opt/websockify/data
      - websockify-config:/opt/websockify/config

volumes:
  postgres-data:
    driver: local
  websockify-data:
    driver: local
  websockify-config:
    driver: local
