# Sample workflow for building and testing a Next.js site
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Test Next.js build

on:
  # Runs on pushes targeting the integration and main branches
  push:
    branches: ["integration", "main"]

  # Runs on open, reopened, and synchronized pull requests targeting the integration and main branches
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["integration", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  POSTGRES_PORT: 5432
  POSTGRES_PASSWORD: postgres
  PRISMA_DB_URL: "postgresql://postgres:postgres@localhost:5432/postgres"

jobs:
  # ESLint job
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Hydrogen"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Install dependencies with --legacy-peer-deps and --no-package-lock to avoid conflicts and prevent generating lock file
      - name: Install dependencies
        run: npm install --no-package-lock --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

  # Build job, dependent on eslint job
  build:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Hydrogen"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install --no-package-lock --legacy-peer-deps

      # Create Prisma Generator
      - name: Create Prisma Generator
        run: |
          if grep -q '^model*' ${{ github.workspace }}/prisma/schema.prisma; then
            npx prisma generate
          else
            echo "No models defined in 'prisma.schema'. Prisma Client NOT generated"
          fi

      - name: Build with Next.js
        run: npm run build
